import './pages/colors-and-text/colors-and-text'
import './pages/form-elements/form-elements'
import './pages/cards/cards'
import './pages/headers-and-footers/headers-and-footers'
import './pages/landing-page/landing-page'
import './pages/search-room/search-room'
